// Code generated by gowsdl DO NOT EDIT.

package ejbcaws

import (
	"context"
	"encoding/xml"
	"github.com/hooklift/gowsdl/soap"
	"time"
)

// against "unused imports"
var _ time.Time
var _ xml.Name

type AnyType struct {
	InnerXML string `xml:",innerxml"`
}

type AnyURI string

type NCName string

type GetHardTokenData struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ getHardTokenData"`

	Arg0 string `xml:"arg0,omitempty" json:"arg0,omitempty"`

	Arg1 bool `xml:"arg1,omitempty" json:"arg1,omitempty"`

	Arg2 bool `xml:"arg2,omitempty" json:"arg2,omitempty"`
}

type GetHardTokenDataResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ getHardTokenDataResponse"`

	Return_ *HardTokenDataWS `xml:"return,omitempty" json:"return,omitempty"`
}

type HardTokenDataWS struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ hardTokenDataWS"`

	Certificates []*Certificate `xml:"certificates,omitempty" json:"certificates,omitempty"`

	Copies []*string `xml:"copies,omitempty" json:"copies,omitempty"`

	CopyOfSN string `xml:"copyOfSN,omitempty" json:"copyOfSN,omitempty"`

	CreateTime soap.XSDDateTime `xml:"createTime,omitempty" json:"createTime,omitempty"`

	EncKeyKeyRecoverable bool `xml:"encKeyKeyRecoverable,omitempty" json:"encKeyKeyRecoverable,omitempty"`

	HardTokenSN string `xml:"hardTokenSN,omitempty" json:"hardTokenSN,omitempty"`

	Label string `xml:"label,omitempty" json:"label,omitempty"`

	ModifyTime soap.XSDDateTime `xml:"modifyTime,omitempty" json:"modifyTime,omitempty"`

	PinDatas []*PinDataWS `xml:"pinDatas,omitempty" json:"pinDatas,omitempty"`

	TokenType int32 `xml:"tokenType,omitempty" json:"tokenType,omitempty"`
}

type Certificate struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ certificate"`

	*TokenCertificateResponseWS

	CertificateData []byte `xml:"certificateData,omitempty" json:"certificateData,omitempty"`
}

type TokenCertificateResponseWS struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ tokenCertificateResponseWS"`

	Certificate *Certificate `xml:"certificate,omitempty" json:"certificate,omitempty"`

	KeyStore *KeyStore `xml:"keyStore,omitempty" json:"keyStore,omitempty"`

	Type_ int32 `xml:"type,omitempty" json:"type,omitempty"`
}

type KeyStore struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ keyStore"`

	*TokenCertificateResponseWS

	KeystoreData []byte `xml:"keystoreData,omitempty" json:"keystoreData,omitempty"`
}

type PinDataWS struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ pinDataWS"`

	InitialPIN string `xml:"initialPIN,omitempty" json:"initialPIN,omitempty"`

	PUK string `xml:"PUK,omitempty" json:"PUK,omitempty"`

	Type_ int32 `xml:"type,omitempty" json:"type,omitempty"`
}

type ErrorCode struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ errorCode"`

	InternalErrorCode string `xml:"internalErrorCode,omitempty" json:"internalErrorCode,omitempty"`
}

type GetProfile struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ getProfile"`

	Arg0 int32 `xml:"arg0,omitempty" json:"arg0,omitempty"`

	Arg1 string `xml:"arg1,omitempty" json:"arg1,omitempty"`
}

type GetProfileResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ getProfileResponse"`

	Return_ []byte `xml:"return,omitempty" json:"return,omitempty"`
}

type CreateCryptoToken struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ createCryptoToken"`

	Arg0 string `xml:"arg0,omitempty" json:"arg0,omitempty"`

	Arg1 string `xml:"arg1,omitempty" json:"arg1,omitempty"`

	Arg2 string `xml:"arg2,omitempty" json:"arg2,omitempty"`

	Arg3 bool `xml:"arg3,omitempty" json:"arg3,omitempty"`

	Arg4 []*KeyValuePair `xml:"arg4,omitempty" json:"arg4,omitempty"`
}

type KeyValuePair struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ keyValuePair"`

	Key string `xml:"key,omitempty" json:"key,omitempty"`

	Value string `xml:"value,omitempty" json:"value,omitempty"`
}

type CreateCryptoTokenResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ createCryptoTokenResponse"`
}

type CrmfRequest struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ crmfRequest"`

	Arg0 string `xml:"arg0,omitempty" json:"arg0,omitempty"`

	Arg1 string `xml:"arg1,omitempty" json:"arg1,omitempty"`

	Arg2 string `xml:"arg2,omitempty" json:"arg2,omitempty"`

	Arg3 string `xml:"arg3,omitempty" json:"arg3,omitempty"`

	Arg4 string `xml:"arg4,omitempty" json:"arg4,omitempty"`
}

type CrmfRequestResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ crmfRequestResponse"`

	Return_ *CertificateResponse `xml:"return,omitempty" json:"return,omitempty"`
}

type CertificateResponse struct {
// UPDATED BY TS	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ certificateResponse"`
XMLName xml.Name `xml:"return"`
	Data []byte `xml:"data,omitempty" json:"data,omitempty"`

	ResponseType string `xml:"responseType,omitempty" json:"responseType,omitempty"`
}

type FindUser struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ findUser"`

	Arg0 *UserMatch `xml:"arg0,omitempty" json:"arg0,omitempty"`
}

type UserMatch struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ userMatch"`

	Matchtype int32 `xml:"matchtype,omitempty" json:"matchtype,omitempty"`

	Matchvalue string `xml:"matchvalue,omitempty" json:"matchvalue,omitempty"`

	Matchwith int32 `xml:"matchwith,omitempty" json:"matchwith,omitempty"`
}

type FindUserResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ findUserResponse"`

	Return_ []*UserDataVOWS `xml:"return,omitempty" json:"return,omitempty"`
}

type UserDataVOWS struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ userDataVOWS"`

	CaName string `xml:"caName,omitempty" json:"caName,omitempty"`

	CardNumber string `xml:"cardNumber,omitempty" json:"cardNumber,omitempty"`

	CertificateProfileName string `xml:"certificateProfileName,omitempty" json:"certificateProfileName,omitempty"`

	CertificateSerialNumber int32 `xml:"certificateSerialNumber,omitempty" json:"certificateSerialNumber,omitempty"`

	ClearPwd bool `xml:"clearPwd,omitempty" json:"clearPwd,omitempty"`

	Email string `xml:"email,omitempty" json:"email,omitempty"`

	EndEntityProfileName string `xml:"endEntityProfileName,omitempty" json:"endEntityProfileName,omitempty"`

	EndTime string `xml:"endTime,omitempty" json:"endTime,omitempty"`

	ExtendedInformation []*ExtendedInformationWS `xml:"extendedInformation,omitempty" json:"extendedInformation,omitempty"`

	HardTokenIssuerName string `xml:"hardTokenIssuerName,omitempty" json:"hardTokenIssuerName,omitempty"`

	KeyRecoverable bool `xml:"keyRecoverable,omitempty" json:"keyRecoverable,omitempty"`

	Password string `xml:"password,omitempty" json:"password,omitempty"`

	SendNotification bool `xml:"sendNotification,omitempty" json:"sendNotification,omitempty"`

	StartTime string `xml:"startTime,omitempty" json:"startTime,omitempty"`

	Status int32 `xml:"status,omitempty" json:"status,omitempty"`

	SubjectAltName string `xml:"subjectAltName,omitempty" json:"subjectAltName,omitempty"`

	SubjectDN string `xml:"subjectDN,omitempty" json:"subjectDN,omitempty"`

	TokenType string `xml:"tokenType,omitempty" json:"tokenType,omitempty"`

	Username string `xml:"username,omitempty" json:"username,omitempty"`
}

type ExtendedInformationWS struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ extendedInformationWS"`

	Name string `xml:"name,omitempty" json:"name,omitempty"`

	Value string `xml:"value,omitempty" json:"value,omitempty"`
}

type GetRemainingNumberOfApprovals struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ getRemainingNumberOfApprovals"`

	Arg0 int32 `xml:"arg0,omitempty" json:"arg0,omitempty"`
}

type GetRemainingNumberOfApprovalsResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ getRemainingNumberOfApprovalsResponse"`

	Return_ int32 `xml:"return,omitempty" json:"return,omitempty"`
}

type GenTokenCertificates struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ genTokenCertificates"`

	Arg0 *UserDataVOWS `xml:"arg0,omitempty" json:"arg0,omitempty"`

	Arg1 []*TokenCertificateRequestWS `xml:"arg1,omitempty" json:"arg1,omitempty"`

	Arg2 *HardTokenDataWS `xml:"arg2,omitempty" json:"arg2,omitempty"`

	Arg3 bool `xml:"arg3,omitempty" json:"arg3,omitempty"`

	Arg4 bool `xml:"arg4,omitempty" json:"arg4,omitempty"`
}

type TokenCertificateRequestWS struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ tokenCertificateRequestWS"`

	CAName string `xml:"cAName,omitempty" json:"cAName,omitempty"`

	CertificateProfileName string `xml:"certificateProfileName,omitempty" json:"certificateProfileName,omitempty"`

	Keyalg string `xml:"keyalg,omitempty" json:"keyalg,omitempty"`

	Keyspec string `xml:"keyspec,omitempty" json:"keyspec,omitempty"`

	Pkcs10Data []byte `xml:"pkcs10Data,omitempty" json:"pkcs10Data,omitempty"`

	TokenType string `xml:"tokenType,omitempty" json:"tokenType,omitempty"`

	Type_ int32 `xml:"type,omitempty" json:"type,omitempty"`

	ValidityIdDays string `xml:"validityIdDays,omitempty" json:"validityIdDays,omitempty"`
}

type GenTokenCertificatesResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ genTokenCertificatesResponse"`

	Return_ []*TokenCertificateResponseWS `xml:"return,omitempty" json:"return,omitempty"`
}

type GetCertificatesByExpirationTimeAndType struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ getCertificatesByExpirationTimeAndType"`

	Arg0 int64 `xml:"arg0,omitempty" json:"arg0,omitempty"`

	Arg1 int32 `xml:"arg1,omitempty" json:"arg1,omitempty"`

	Arg2 int32 `xml:"arg2,omitempty" json:"arg2,omitempty"`
}

type GetCertificatesByExpirationTimeAndTypeResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ getCertificatesByExpirationTimeAndTypeResponse"`

	Return_ []*Certificate `xml:"return,omitempty" json:"return,omitempty"`
}

type RevokeCertBackdated struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ revokeCertBackdated"`

	Arg0 string `xml:"arg0,omitempty" json:"arg0,omitempty"`

	Arg1 string `xml:"arg1,omitempty" json:"arg1,omitempty"`

	Arg2 int32 `xml:"arg2,omitempty" json:"arg2,omitempty"`

	Arg3 string `xml:"arg3,omitempty" json:"arg3,omitempty"`
}

type RevokeCertBackdatedResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ revokeCertBackdatedResponse"`
}

type CheckRevokationStatus struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ checkRevokationStatus"`

	Arg0 string `xml:"arg0,omitempty" json:"arg0,omitempty"`

	Arg1 string `xml:"arg1,omitempty" json:"arg1,omitempty"`
}

type CheckRevokationStatusResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ checkRevokationStatusResponse"`

	Return_ *RevokeStatus `xml:"return,omitempty" json:"return,omitempty"`
}

type RevokeStatus struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ revokeStatus"`

	CertificateSN string `xml:"certificateSN,omitempty" json:"certificateSN,omitempty"`

	IssuerDN string `xml:"issuerDN,omitempty" json:"issuerDN,omitempty"`

	Reason int32 `xml:"reason,omitempty" json:"reason,omitempty"`

	RevocationDate soap.XSDDateTime `xml:"revocationDate,omitempty" json:"revocationDate,omitempty"`
}

type GenerateCryptoTokenKeys struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ generateCryptoTokenKeys"`

	Arg0 string `xml:"arg0,omitempty" json:"arg0,omitempty"`

	Arg1 string `xml:"arg1,omitempty" json:"arg1,omitempty"`

	Arg2 string `xml:"arg2,omitempty" json:"arg2,omitempty"`
}

type GenerateCryptoTokenKeysResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ generateCryptoTokenKeysResponse"`
}

type KeyRecoverNewest struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ keyRecoverNewest"`

	Arg0 string `xml:"arg0,omitempty" json:"arg0,omitempty"`
}

type KeyRecoverNewestResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ keyRecoverNewestResponse"`
}

type EditUser struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ editUser"`

	Arg0 *UserDataVOWS `xml:"arg0,omitempty" json:"arg0,omitempty"`
}

type EditUserResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ editUserResponse"`
}

type SpkacRequest struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ spkacRequest"`

	Arg0 string `xml:"arg0,omitempty" json:"arg0,omitempty"`

	Arg1 string `xml:"arg1,omitempty" json:"arg1,omitempty"`

	Arg2 string `xml:"arg2,omitempty" json:"arg2,omitempty"`

	Arg3 string `xml:"arg3,omitempty" json:"arg3,omitempty"`

	Arg4 string `xml:"arg4,omitempty" json:"arg4,omitempty"`
}

type SpkacRequestResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ spkacRequestResponse"`

	Return_ *CertificateResponse `xml:"return,omitempty" json:"return,omitempty"`
}

type GetLatestCRLPartition struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ getLatestCRLPartition"`

	Arg0 string `xml:"arg0,omitempty" json:"arg0,omitempty"`

	Arg1 bool `xml:"arg1,omitempty" json:"arg1,omitempty"`

	Arg2 int32 `xml:"arg2,omitempty" json:"arg2,omitempty"`
}

type GetLatestCRLPartitionResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ getLatestCRLPartitionResponse"`

	Return_ []byte `xml:"return,omitempty" json:"return,omitempty"`
}

type GetLastCAChain struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ getLastCAChain"`

	Arg0 string `xml:"arg0,omitempty" json:"arg0,omitempty"`
}

type GetLastCAChainResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ getLastCAChainResponse"`

	Return_ []*Certificate `xml:"return,omitempty" json:"return,omitempty"`
}

type AddSubjectToRole struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ addSubjectToRole"`

	Arg0 string `xml:"arg0,omitempty" json:"arg0,omitempty"`

	Arg1 string `xml:"arg1,omitempty" json:"arg1,omitempty"`

	Arg2 string `xml:"arg2,omitempty" json:"arg2,omitempty"`

	Arg3 string `xml:"arg3,omitempty" json:"arg3,omitempty"`

	Arg4 string `xml:"arg4,omitempty" json:"arg4,omitempty"`
}

type AddSubjectToRoleResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ addSubjectToRoleResponse"`
}

type FindCerts struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ findCerts"`

	Arg0 string `xml:"arg0,omitempty" json:"arg0,omitempty"`

	Arg1 bool `xml:"arg1,omitempty" json:"arg1,omitempty"`
}

type FindCertsResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ findCertsResponse"`

	Return_ []*Certificate `xml:"return,omitempty" json:"return,omitempty"`
}

type DeleteUserDataFromSource struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ deleteUserDataFromSource"`

	Arg0 []string `xml:"arg0,omitempty" json:"arg0,omitempty"`

	Arg1 string `xml:"arg1,omitempty" json:"arg1,omitempty"`

	Arg2 bool `xml:"arg2,omitempty" json:"arg2,omitempty"`
}

type DeleteUserDataFromSourceResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ deleteUserDataFromSourceResponse"`

	Return_ bool `xml:"return,omitempty" json:"return,omitempty"`
}

type CertificateRequest struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ certificateRequest"`

	Arg0 *UserDataVOWS `xml:"arg0,omitempty" json:"arg0,omitempty"`

	Arg1 string `xml:"arg1,omitempty" json:"arg1,omitempty"`

	Arg2 int32 `xml:"arg2,omitempty" json:"arg2,omitempty"`

	Arg3 string `xml:"arg3,omitempty" json:"arg3,omitempty"`

	Arg4 string `xml:"arg4,omitempty" json:"arg4,omitempty"`
}

type CertificateRequestResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ certificateRequestResponse"`

	Return_ *CertificateResponse `xml:"return,omitempty" json:"return,omitempty"`
}

type CustomLog struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ customLog"`

	Arg0 int32 `xml:"arg0,omitempty" json:"arg0,omitempty"`

	Arg1 string `xml:"arg1,omitempty" json:"arg1,omitempty"`

	Arg2 string `xml:"arg2,omitempty" json:"arg2,omitempty"`

	Arg3 string `xml:"arg3,omitempty" json:"arg3,omitempty"`

	Arg4 *Certificate `xml:"arg4,omitempty" json:"arg4,omitempty"`

	Arg5 string `xml:"arg5,omitempty" json:"arg5,omitempty"`
}

type CustomLogResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ customLogResponse"`
}

type GetEjbcaVersion struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ getEjbcaVersion"`
}

type GetEjbcaVersionResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ getEjbcaVersionResponse"`

	Return_ string `xml:"return,omitempty" json:"return,omitempty"`
}

type GetAuthorizedEndEntityProfiles struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ getAuthorizedEndEntityProfiles"`
}

type GetAuthorizedEndEntityProfilesResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ getAuthorizedEndEntityProfilesResponse"`

	Return_ []*NameAndId `xml:"return,omitempty" json:"return,omitempty"`
}

type NameAndId struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ nameAndId"`

	Id int32 `xml:"id,omitempty" json:"id,omitempty"`

	Name string `xml:"name,omitempty" json:"name,omitempty"`
}

type ExistsHardToken struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ existsHardToken"`

	Arg0 string `xml:"arg0,omitempty" json:"arg0,omitempty"`
}

type ExistsHardTokenResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ existsHardTokenResponse"`

	Return_ bool `xml:"return,omitempty" json:"return,omitempty"`
}

type CvcRequest struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ cvcRequest"`

	Arg0 string `xml:"arg0,omitempty" json:"arg0,omitempty"`

	Arg1 string `xml:"arg1,omitempty" json:"arg1,omitempty"`

	Arg2 string `xml:"arg2,omitempty" json:"arg2,omitempty"`
}

type CvcRequestResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ cvcRequestResponse"`

	Return_ []*Certificate `xml:"return,omitempty" json:"return,omitempty"`
}

type IsAuthorized struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ isAuthorized"`

	Arg0 string `xml:"arg0,omitempty" json:"arg0,omitempty"`
}

type IsAuthorizedResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ isAuthorizedResponse"`

	Return_ bool `xml:"return,omitempty" json:"return,omitempty"`
}

type KeyRecoverEnroll struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ keyRecoverEnroll"`

	Arg0 string `xml:"arg0,omitempty" json:"arg0,omitempty"`

	Arg1 string `xml:"arg1,omitempty" json:"arg1,omitempty"`

	Arg2 string `xml:"arg2,omitempty" json:"arg2,omitempty"`

	Arg3 string `xml:"arg3,omitempty" json:"arg3,omitempty"`

	Arg4 string `xml:"arg4,omitempty" json:"arg4,omitempty"`
}

type KeyRecoverEnrollResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ keyRecoverEnrollResponse"`

	Return_ *KeyStore `xml:"return,omitempty" json:"return,omitempty"`
}

type RepublishCertificate struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ republishCertificate"`

	Arg0 string `xml:"arg0,omitempty" json:"arg0,omitempty"`

	Arg1 string `xml:"arg1,omitempty" json:"arg1,omitempty"`
}

type RepublishCertificateResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ republishCertificateResponse"`
}

type CaCertResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ caCertResponse"`

	Arg0 string `xml:"arg0,omitempty" json:"arg0,omitempty"`

	Arg1 []byte `xml:"arg1,omitempty" json:"arg1,omitempty"`

	Arg2 [][]byte `xml:"arg2,omitempty" json:"arg2,omitempty"`

	Arg3 string `xml:"arg3,omitempty" json:"arg3,omitempty"`
}

type CaCertResponseResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ caCertResponseResponse"`
}

type CreateCRL struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ createCRL"`

	Arg0 string `xml:"arg0,omitempty" json:"arg0,omitempty"`
}

type CreateCRLResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ createCRLResponse"`
}

type GetAvailableCAsInProfile struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ getAvailableCAsInProfile"`

	Arg0 int32 `xml:"arg0,omitempty" json:"arg0,omitempty"`
}

type GetAvailableCAsInProfileResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ getAvailableCAsInProfileResponse"`

	Return_ []*NameAndId `xml:"return,omitempty" json:"return,omitempty"`
}

type Pkcs12Req struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ pkcs12Req"`

	Arg0 string `xml:"arg0,omitempty" json:"arg0,omitempty"`

	Arg1 string `xml:"arg1,omitempty" json:"arg1,omitempty"`

	Arg2 string `xml:"arg2,omitempty" json:"arg2,omitempty"`

	Arg3 string `xml:"arg3,omitempty" json:"arg3,omitempty"`

	Arg4 string `xml:"arg4,omitempty" json:"arg4,omitempty"`
}

type Pkcs12ReqResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ pkcs12ReqResponse"`

	Return_ *KeyStore `xml:"return,omitempty" json:"return,omitempty"`
}

type CaCertResponseForRollover struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ caCertResponseForRollover"`

	Arg0 string `xml:"arg0,omitempty" json:"arg0,omitempty"`

	Arg1 []byte `xml:"arg1,omitempty" json:"arg1,omitempty"`

	Arg2 [][]byte `xml:"arg2,omitempty" json:"arg2,omitempty"`

	Arg3 string `xml:"arg3,omitempty" json:"arg3,omitempty"`
}

type CaCertResponseForRolloverResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ caCertResponseForRolloverResponse"`
}

type KeyRecover struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ keyRecover"`

	Arg0 string `xml:"arg0,omitempty" json:"arg0,omitempty"`

	Arg1 string `xml:"arg1,omitempty" json:"arg1,omitempty"`

	Arg2 string `xml:"arg2,omitempty" json:"arg2,omitempty"`
}

type KeyRecoverResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ keyRecoverResponse"`
}

type RevokeCertWithMetadata struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ revokeCertWithMetadata"`

	Arg0 string `xml:"arg0,omitempty" json:"arg0,omitempty"`

	Arg1 string `xml:"arg1,omitempty" json:"arg1,omitempty"`

	Arg2 []*KeyValuePair `xml:"arg2,omitempty" json:"arg2,omitempty"`
}

type RevokeCertWithMetadataResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ revokeCertWithMetadataResponse"`
}

type RolloverCACert struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ rolloverCACert"`

	Arg0 string `xml:"arg0,omitempty" json:"arg0,omitempty"`
}

type RolloverCACertResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ rolloverCACertResponse"`
}

type CaRenewCertRequest struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ caRenewCertRequest"`

	Arg0 string `xml:"arg0,omitempty" json:"arg0,omitempty"`

	Arg1 [][]byte `xml:"arg1,omitempty" json:"arg1,omitempty"`

	Arg2 bool `xml:"arg2,omitempty" json:"arg2,omitempty"`

	Arg3 bool `xml:"arg3,omitempty" json:"arg3,omitempty"`

	Arg4 bool `xml:"arg4,omitempty" json:"arg4,omitempty"`

	Arg5 string `xml:"arg5,omitempty" json:"arg5,omitempty"`
}

type CaRenewCertRequestResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ caRenewCertRequestResponse"`

	Return_ []byte `xml:"return,omitempty" json:"return,omitempty"`
}

type FetchUserData struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ fetchUserData"`

	Arg0 []string `xml:"arg0,omitempty" json:"arg0,omitempty"`

	Arg1 string `xml:"arg1,omitempty" json:"arg1,omitempty"`
}

type FetchUserDataResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ fetchUserDataResponse"`

	Return_ []*UserDataSourceVOWS `xml:"return,omitempty" json:"return,omitempty"`
}

type UserDataSourceVOWS struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ userDataSourceVOWS"`

	IsModifyable []*int32 `xml:"isModifyable,omitempty" json:"isModifyable,omitempty"`

	UserDataVOWS *UserDataVOWS `xml:"userDataVOWS,omitempty" json:"userDataVOWS,omitempty"`
}

/*
type Pkcs10Request struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ pkcs10Request"`

	Arg0 string `xml:"arg0,omitempty" json:"arg0,omitempty"`

	Arg1 string `xml:"arg1,omitempty" json:"arg1,omitempty"`

	Arg2 string `xml:"arg2,omitempty" json:"arg2,omitempty"`

	Arg3 string `xml:"arg3,omitempty" json:"arg3,omitempty"`

	Arg4 string `xml:"arg4,omitempty" json:"arg4,omitempty"`
}
*/

type Pkcs10Request struct {
	XMLName  xml.Name `xml:"ns1:pkcs10Request"`
	XmlnsNs1 string   `xml:"xmlns:ns1,attr"`

	Arg3 string `xml:"arg3,omitempty"`
	Arg2 string `xml:"arg2,omitempty"`
	Arg4 string `xml:"arg4,omitempty"`
	Arg1 string `xml:"arg1,omitempty"`
	Arg0 string `xml:"arg0,omitempty"`
}

type Pkcs10RequestResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ pkcs10RequestResponse"`

	Return_ *CertificateResponse `xml:"return,omitempty" json:"return,omitempty"`
}

type GetHardTokenDatas struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ getHardTokenDatas"`

	Arg0 string `xml:"arg0,omitempty" json:"arg0,omitempty"`

	Arg1 bool `xml:"arg1,omitempty" json:"arg1,omitempty"`

	Arg2 bool `xml:"arg2,omitempty" json:"arg2,omitempty"`
}

type GetHardTokenDatasResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ getHardTokenDatasResponse"`

	Return_ []*HardTokenDataWS `xml:"return,omitempty" json:"return,omitempty"`
}

type RevokeToken struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ revokeToken"`

	Arg0 string `xml:"arg0,omitempty" json:"arg0,omitempty"`

	Arg1 int32 `xml:"arg1,omitempty" json:"arg1,omitempty"`
}

type RevokeTokenResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ revokeTokenResponse"`
}

type SoftTokenRequest struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ softTokenRequest"`

	Arg0 *UserDataVOWS `xml:"arg0,omitempty" json:"arg0,omitempty"`

	Arg1 string `xml:"arg1,omitempty" json:"arg1,omitempty"`

	Arg2 string `xml:"arg2,omitempty" json:"arg2,omitempty"`

	Arg3 string `xml:"arg3,omitempty" json:"arg3,omitempty"`
}

type SoftTokenRequestResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ softTokenRequestResponse"`

	Return_ *KeyStore `xml:"return,omitempty" json:"return,omitempty"`
}

type GetLatestCRL struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ getLatestCRL"`

	Arg0 string `xml:"arg0,omitempty" json:"arg0,omitempty"`

	Arg1 bool `xml:"arg1,omitempty" json:"arg1,omitempty"`
}

type GetLatestCRLResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ getLatestCRLResponse"`

	Return_ []byte `xml:"return,omitempty" json:"return,omitempty"`
}

type EnrollAndIssueSshCertificate struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ enrollAndIssueSshCertificate"`

	Arg0 *UserDataVOWS `xml:"arg0,omitempty" json:"arg0,omitempty"`

	Arg1 *SshRequestMessageWs `xml:"arg1,omitempty" json:"arg1,omitempty"`
}

type SshRequestMessageWs struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ sshRequestMessageWs"`

	AdditionalExtensions struct {
		Entry []struct {
			Key string `xml:"key,omitempty" json:"key,omitempty"`

			Value []byte `xml:"value,omitempty" json:"value,omitempty"`
		} `xml:"entry,omitempty" json:"entry,omitempty"`
	} `xml:"additionalExtensions,omitempty" json:"additionalExtensions,omitempty"`

	Comment string `xml:"comment,omitempty" json:"comment,omitempty"`

	CriticalOptions struct {
		Entry []struct {
			Key string `xml:"key,omitempty" json:"key,omitempty"`

			Value string `xml:"value,omitempty" json:"value,omitempty"`
		} `xml:"entry,omitempty" json:"entry,omitempty"`
	} `xml:"criticalOptions,omitempty" json:"criticalOptions,omitempty"`

	KeyId string `xml:"keyId,omitempty" json:"keyId,omitempty"`

	Principals []*string `xml:"principals,omitempty" json:"principals,omitempty"`

	PublicKey []byte `xml:"publicKey,omitempty" json:"publicKey,omitempty"`
}

type EnrollAndIssueSshCertificateResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ enrollAndIssueSshCertificateResponse"`

	Return_ []byte `xml:"return,omitempty" json:"return,omitempty"`
}

type ImportCaCert struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ importCaCert"`

	Arg0 string `xml:"arg0,omitempty" json:"arg0,omitempty"`

	Arg1 []byte `xml:"arg1,omitempty" json:"arg1,omitempty"`
}

type ImportCaCertResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ importCaCertResponse"`
}

type RemoveSubjectFromRole struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ removeSubjectFromRole"`

	Arg0 string `xml:"arg0,omitempty" json:"arg0,omitempty"`

	Arg1 string `xml:"arg1,omitempty" json:"arg1,omitempty"`

	Arg2 string `xml:"arg2,omitempty" json:"arg2,omitempty"`

	Arg3 string `xml:"arg3,omitempty" json:"arg3,omitempty"`

	Arg4 string `xml:"arg4,omitempty" json:"arg4,omitempty"`
}

type RemoveSubjectFromRoleResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ removeSubjectFromRoleResponse"`
}

type GetAvailableCAs struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ getAvailableCAs"`
}

type GetAvailableCAsResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ getAvailableCAsResponse"`

	Return_ []*NameAndId `xml:"return,omitempty" json:"return,omitempty"`
}

type GetCertificatesByExpirationTimeAndIssuer struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ getCertificatesByExpirationTimeAndIssuer"`

	Arg0 int64 `xml:"arg0,omitempty" json:"arg0,omitempty"`

	Arg1 string `xml:"arg1,omitempty" json:"arg1,omitempty"`

	Arg2 int32 `xml:"arg2,omitempty" json:"arg2,omitempty"`
}

type GetCertificatesByExpirationTimeAndIssuerResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ getCertificatesByExpirationTimeAndIssuerResponse"`

	Return_ []*Certificate `xml:"return,omitempty" json:"return,omitempty"`
}

type UpdateCaCert struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ updateCaCert"`

	Arg0 string `xml:"arg0,omitempty" json:"arg0,omitempty"`

	Arg1 []byte `xml:"arg1,omitempty" json:"arg1,omitempty"`
}

type UpdateCaCertResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ updateCaCertResponse"`
}

type GetLastCertChain struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ getLastCertChain"`

	Arg0 string `xml:"arg0,omitempty" json:"arg0,omitempty"`
}

type GetLastCertChainResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ getLastCertChainResponse"`

	Return_ []*Certificate `xml:"return,omitempty" json:"return,omitempty"`
}

type GetCertificatesByExpirationTime struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ getCertificatesByExpirationTime"`

	Arg0 int64 `xml:"arg0,omitempty" json:"arg0,omitempty"`

	Arg1 int32 `xml:"arg1,omitempty" json:"arg1,omitempty"`
}

type GetCertificatesByExpirationTimeResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ getCertificatesByExpirationTimeResponse"`

	Return_ []*Certificate `xml:"return,omitempty" json:"return,omitempty"`
}

type GetSshCaPublicKey struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ getSshCaPublicKey"`

	Arg0 string `xml:"arg0,omitempty" json:"arg0,omitempty"`
}

type GetSshCaPublicKeyResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ getSshCaPublicKeyResponse"`

	Return_ []byte `xml:"return,omitempty" json:"return,omitempty"`
}

type GetAvailableCertificateProfiles struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ getAvailableCertificateProfiles"`

	Arg0 int32 `xml:"arg0,omitempty" json:"arg0,omitempty"`
}

type GetAvailableCertificateProfilesResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ getAvailableCertificateProfilesResponse"`

	Return_ []*NameAndId `xml:"return,omitempty" json:"return,omitempty"`
}

type CreateCA struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ createCA"`

	Arg0 string `xml:"arg0,omitempty" json:"arg0,omitempty"`

	Arg1 string `xml:"arg1,omitempty" json:"arg1,omitempty"`

	Arg2 string `xml:"arg2,omitempty" json:"arg2,omitempty"`

	Arg3 int64 `xml:"arg3,omitempty" json:"arg3,omitempty"`

	Arg4 string `xml:"arg4,omitempty" json:"arg4,omitempty"`

	Arg5 string `xml:"arg5,omitempty" json:"arg5,omitempty"`

	Arg6 int32 `xml:"arg6,omitempty" json:"arg6,omitempty"`

	Arg7 string `xml:"arg7,omitempty" json:"arg7,omitempty"`

	Arg8 []*KeyValuePair `xml:"arg8,omitempty" json:"arg8,omitempty"`

	Arg9 []*KeyValuePair `xml:"arg9,omitempty" json:"arg9,omitempty"`
}

type CreateCAResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ createCAResponse"`
}

type IsApproved struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ isApproved"`

	Arg0 int32 `xml:"arg0,omitempty" json:"arg0,omitempty"`
}

type IsApprovedResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ isApprovedResponse"`

	Return_ int32 `xml:"return,omitempty" json:"return,omitempty"`
}

type CreateExternallySignedCa struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ createExternallySignedCa"`

	Arg0 string `xml:"arg0,omitempty" json:"arg0,omitempty"`

	Arg1 string `xml:"arg1,omitempty" json:"arg1,omitempty"`

	Arg2 string `xml:"arg2,omitempty" json:"arg2,omitempty"`

	Arg3 int64 `xml:"arg3,omitempty" json:"arg3,omitempty"`

	Arg4 string `xml:"arg4,omitempty" json:"arg4,omitempty"`

	Arg5 string `xml:"arg5,omitempty" json:"arg5,omitempty"`

	Arg6 string `xml:"arg6,omitempty" json:"arg6,omitempty"`

	Arg7 []*KeyValuePair `xml:"arg7,omitempty" json:"arg7,omitempty"`

	Arg8 []*KeyValuePair `xml:"arg8,omitempty" json:"arg8,omitempty"`
}

type CreateExternallySignedCaResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ createExternallySignedCaResponse"`

	Return_ []byte `xml:"return,omitempty" json:"return,omitempty"`
}

type RevokeUser struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ revokeUser"`

	Arg0 string `xml:"arg0,omitempty" json:"arg0,omitempty"`

	Arg1 int32 `xml:"arg1,omitempty" json:"arg1,omitempty"`

	Arg2 bool `xml:"arg2,omitempty" json:"arg2,omitempty"`
}

type RevokeUserResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ revokeUserResponse"`
}

type RevokeCert struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ revokeCert"`

	Arg0 string `xml:"arg0,omitempty" json:"arg0,omitempty"`

	Arg1 string `xml:"arg1,omitempty" json:"arg1,omitempty"`

	Arg2 int32 `xml:"arg2,omitempty" json:"arg2,omitempty"`
}

type RevokeCertResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ revokeCertResponse"`
}

type GetCertificate struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ getCertificate"`

	Arg0 string `xml:"arg0,omitempty" json:"arg0,omitempty"`

	Arg1 string `xml:"arg1,omitempty" json:"arg1,omitempty"`
}

type GetCertificateResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ getCertificateResponse"`

	Return_ *Certificate `xml:"return,omitempty" json:"return,omitempty"`
}

type GetPublisherQueueLength struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ getPublisherQueueLength"`

	Arg0 string `xml:"arg0,omitempty" json:"arg0,omitempty"`
}

type GetPublisherQueueLengthResponse struct {
	XMLName xml.Name `xml:"http://ws.protocol.core.ejbca.org/ getPublisherQueueLengthResponse"`

	Return_ int32 `xml:"return,omitempty" json:"return,omitempty"`
}

type NotFoundException struct {
	ErrorCode *ErrorCode `xml:"errorCode,omitempty" json:"errorCode,omitempty"`

	Message string `xml:"message,omitempty" json:"message,omitempty"`
}

type ApprovalException struct {
	ErrorCode *ErrorCode `xml:"errorCode,omitempty" json:"errorCode,omitempty"`

	Message string `xml:"message,omitempty" json:"message,omitempty"`
}

type EjbcaException struct {
	ErrorCode *ErrorCode `xml:"errorCode,omitempty" json:"errorCode,omitempty"`

	Message string `xml:"message,omitempty" json:"message,omitempty"`
}

type AuthorizationDeniedException struct {
	Message string `xml:"message,omitempty" json:"message,omitempty"`
}

type UnknownProfileTypeException struct {
	ErrorCode *ErrorCode `xml:"errorCode,omitempty" json:"errorCode,omitempty"`

	Message string `xml:"message,omitempty" json:"message,omitempty"`
}

type CesecoreException struct {
	ErrorCode *ErrorCode `xml:"errorCode,omitempty" json:"errorCode,omitempty"`

	Message string `xml:"message,omitempty" json:"message,omitempty"`
}

type IllegalQueryException struct {
	Message string `xml:"message,omitempty" json:"message,omitempty"`
}

type ApprovalRequestExpiredException struct {
	Message string `xml:"message,omitempty" json:"message,omitempty"`
}

type AlreadyRevokedException struct {
	ErrorCode *ErrorCode `xml:"errorCode,omitempty" json:"errorCode,omitempty"`

	Message string `xml:"message,omitempty" json:"message,omitempty"`
}

type RevokeBackDateNotAllowedForProfileException struct {
	ErrorCode *ErrorCode `xml:"errorCode,omitempty" json:"errorCode,omitempty"`

	Message string `xml:"message,omitempty" json:"message,omitempty"`
}

type CADoesntExistsException struct {
	ErrorCode *ErrorCode `xml:"errorCode,omitempty" json:"errorCode,omitempty"`

	Message string `xml:"message,omitempty" json:"message,omitempty"`
}

type WaitingForApprovalException struct {
	RequestId int32 `xml:"requestId,omitempty" json:"requestId,omitempty"`

	Message string `xml:"message,omitempty" json:"message,omitempty"`
}

type UserDoesntFullfillEndEntityProfile struct {
	Message string `xml:"message,omitempty" json:"message,omitempty"`
}

type CertificateExpiredException struct {
	Message string `xml:"message,omitempty" json:"message,omitempty"`
}

type CAOfflineException struct {
	ErrorCode *ErrorCode `xml:"errorCode,omitempty" json:"errorCode,omitempty"`

	Message string `xml:"message,omitempty" json:"message,omitempty"`
}

type DeltaCrlException struct {
	ErrorCode *ErrorCode `xml:"errorCode,omitempty" json:"errorCode,omitempty"`

	Message string `xml:"message,omitempty" json:"message,omitempty"`
}

type CryptoTokenOfflineException struct {
	ErrorCode *ErrorCode `xml:"errorCode,omitempty" json:"errorCode,omitempty"`

	Message string `xml:"message,omitempty" json:"message,omitempty"`
}

type CertificateProfileDoesNotExistException struct {
	ErrorCode *ErrorCode `xml:"errorCode,omitempty" json:"errorCode,omitempty"`

	Message string `xml:"message,omitempty" json:"message,omitempty"`
}

type EndEntityProfileValidationException struct {
	Message string `xml:"message,omitempty" json:"message,omitempty"`
}

type SshKeyException struct {
	Message string `xml:"message,omitempty" json:"message,omitempty"`
}

type EjbcaWS interface {

	// Error can be either of the following types:
	//
	//   - ApprovalException
	//   - EjbcaException
	//   - NotFoundException

	GetHardTokenData(request *GetHardTokenData) (*GetHardTokenDataResponse, error)

	GetHardTokenDataContext(ctx context.Context, request *GetHardTokenData) (*GetHardTokenDataResponse, error)

	// Error can be either of the following types:
	//
	//   - AuthorizationDeniedException
	//   - EjbcaException
	//   - UnknownProfileTypeException

	GetProfile(request *GetProfile) (*GetProfileResponse, error)

	GetProfileContext(ctx context.Context, request *GetProfile) (*GetProfileResponse, error)

	// Error can be either of the following types:
	//
	//   - AuthorizationDeniedException
	//   - EjbcaException

	CreateCryptoToken(request *CreateCryptoToken) (*CreateCryptoTokenResponse, error)

	CreateCryptoTokenContext(ctx context.Context, request *CreateCryptoToken) (*CreateCryptoTokenResponse, error)

	// Error can be either of the following types:
	//
	//   - AuthorizationDeniedException
	//   - EjbcaException
	//   - CesecoreException
	//   - NotFoundException

	CrmfRequest(request *CrmfRequest) (*CrmfRequestResponse, error)

	CrmfRequestContext(ctx context.Context, request *CrmfRequest) (*CrmfRequestResponse, error)

	// Error can be either of the following types:
	//
	//   - AuthorizationDeniedException
	//   - EjbcaException
	//   - IllegalQueryException

	FindUser(request *FindUser) (*FindUserResponse, error)

	FindUserContext(ctx context.Context, request *FindUser) (*FindUserResponse, error)

	// Error can be either of the following types:
	//
	//   - ApprovalException
	//   - AuthorizationDeniedException
	//   - ApprovalRequestExpiredException

	GetRemainingNumberOfApprovals(request *GetRemainingNumberOfApprovals) (*GetRemainingNumberOfApprovalsResponse, error)

	GetRemainingNumberOfApprovalsContext(ctx context.Context, request *GetRemainingNumberOfApprovals) (*GetRemainingNumberOfApprovalsResponse, error)

	// Error can be either of the following types:
	//
	//   - ApprovalException
	//   - EjbcaException

	GenTokenCertificates(request *GenTokenCertificates) (*GenTokenCertificatesResponse, error)

	GenTokenCertificatesContext(ctx context.Context, request *GenTokenCertificates) (*GenTokenCertificatesResponse, error)

	// Error can be either of the following types:
	//
	//   - EjbcaException

	GetCertificatesByExpirationTimeAndType(request *GetCertificatesByExpirationTimeAndType) (*GetCertificatesByExpirationTimeAndTypeResponse, error)

	GetCertificatesByExpirationTimeAndTypeContext(ctx context.Context, request *GetCertificatesByExpirationTimeAndType) (*GetCertificatesByExpirationTimeAndTypeResponse, error)

	// Error can be either of the following types:
	//
	//   - ApprovalException
	//   - AuthorizationDeniedException
	//   - EjbcaException
	//   - WaitingForApprovalException
	//   - NotFoundException
	//   - AlreadyRevokedException
	//   - RevokeBackDateNotAllowedForProfileException
	//   - CADoesntExistsException

	RevokeCertBackdated(request *RevokeCertBackdated) (*RevokeCertBackdatedResponse, error)

	RevokeCertBackdatedContext(ctx context.Context, request *RevokeCertBackdated) (*RevokeCertBackdatedResponse, error)

	// Error can be either of the following types:
	//
	//   - AuthorizationDeniedException
	//   - EjbcaException
	//   - CADoesntExistsException

	CheckRevokationStatus(request *CheckRevokationStatus) (*CheckRevokationStatusResponse, error)

	CheckRevokationStatusContext(ctx context.Context, request *CheckRevokationStatus) (*CheckRevokationStatusResponse, error)

	// Error can be either of the following types:
	//
	//   - AuthorizationDeniedException
	//   - EjbcaException

	GenerateCryptoTokenKeys(request *GenerateCryptoTokenKeys) (*GenerateCryptoTokenKeysResponse, error)

	GenerateCryptoTokenKeysContext(ctx context.Context, request *GenerateCryptoTokenKeys) (*GenerateCryptoTokenKeysResponse, error)

	// Error can be either of the following types:
	//
	//   - ApprovalException
	//   - AuthorizationDeniedException
	//   - EjbcaException
	//   - WaitingForApprovalException
	//   - NotFoundException
	//   - CADoesntExistsException

	KeyRecoverNewest(request *KeyRecoverNewest) (*KeyRecoverNewestResponse, error)

	KeyRecoverNewestContext(ctx context.Context, request *KeyRecoverNewest) (*KeyRecoverNewestResponse, error)

	// Error can be either of the following types:
	//
	//   - ApprovalException
	//   - AuthorizationDeniedException
	//   - UserDoesntFullfillEndEntityProfile
	//   - EjbcaException
	//   - WaitingForApprovalException
	//   - CADoesntExistsException

	EditUser(request *EditUser) (*EditUserResponse, error)

	EditUserContext(ctx context.Context, request *EditUser) (*EditUserResponse, error)

	// Error can be either of the following types:
	//
	//   - AuthorizationDeniedException
	//   - EjbcaException
	//   - CesecoreException
	//   - NotFoundException

	SpkacRequest(request *SpkacRequest) (*SpkacRequestResponse, error)

	SpkacRequestContext(ctx context.Context, request *SpkacRequest) (*SpkacRequestResponse, error)

	// Error can be either of the following types:
	//
	//   - EjbcaException
	//   - CADoesntExistsException

	GetLatestCRLPartition(request *GetLatestCRLPartition) (*GetLatestCRLPartitionResponse, error)

	GetLatestCRLPartitionContext(ctx context.Context, request *GetLatestCRLPartition) (*GetLatestCRLPartitionResponse, error)

	// Error can be either of the following types:
	//
	//   - AuthorizationDeniedException
	//   - EjbcaException
	//   - CADoesntExistsException

	GetLastCAChain(request *GetLastCAChain) (*GetLastCAChainResponse, error)

	GetLastCAChainContext(ctx context.Context, request *GetLastCAChain) (*GetLastCAChainResponse, error)

	// Error can be either of the following types:
	//
	//   - AuthorizationDeniedException
	//   - EjbcaException

	AddSubjectToRole(request *AddSubjectToRole) (*AddSubjectToRoleResponse, error)

	AddSubjectToRoleContext(ctx context.Context, request *AddSubjectToRole) (*AddSubjectToRoleResponse, error)

	// Error can be either of the following types:
	//
	//   - AuthorizationDeniedException
	//   - EjbcaException

	FindCerts(request *FindCerts) (*FindCertsResponse, error)

	FindCertsContext(ctx context.Context, request *FindCerts) (*FindCertsResponse, error)

	// Error can be either of the following types:
	//
	//   - AuthorizationDeniedException
	//   - EjbcaException

	DeleteUserDataFromSource(request *DeleteUserDataFromSource) (*DeleteUserDataFromSourceResponse, error)

	DeleteUserDataFromSourceContext(ctx context.Context, request *DeleteUserDataFromSource) (*DeleteUserDataFromSourceResponse, error)

	// Error can be either of the following types:
	//
	//   - ApprovalException
	//   - AuthorizationDeniedException
	//   - UserDoesntFullfillEndEntityProfile
	//   - EjbcaException
	//   - NotFoundException

	CertificateRequest(request *CertificateRequest) (*CertificateRequestResponse, error)

	CertificateRequestContext(ctx context.Context, request *CertificateRequest) (*CertificateRequestResponse, error)

	// Error can be either of the following types:
	//
	//   - AuthorizationDeniedException
	//   - EjbcaException
	//   - CADoesntExistsException

	CustomLog(request *CustomLog) (*CustomLogResponse, error)

	CustomLogContext(ctx context.Context, request *CustomLog) (*CustomLogResponse, error)

	GetEjbcaVersion(request *GetEjbcaVersion) (*GetEjbcaVersionResponse, error)

	GetEjbcaVersionContext(ctx context.Context, request *GetEjbcaVersion) (*GetEjbcaVersionResponse, error)

	// Error can be either of the following types:
	//
	//   - AuthorizationDeniedException
	//   - EjbcaException

	GetAuthorizedEndEntityProfiles(request *GetAuthorizedEndEntityProfiles) (*GetAuthorizedEndEntityProfilesResponse, error)

	GetAuthorizedEndEntityProfilesContext(ctx context.Context, request *GetAuthorizedEndEntityProfiles) (*GetAuthorizedEndEntityProfilesResponse, error)

	// Error can be either of the following types:
	//
	//   - EjbcaException

	ExistsHardToken(request *ExistsHardToken) (*ExistsHardTokenResponse, error)

	ExistsHardTokenContext(ctx context.Context, request *ExistsHardToken) (*ExistsHardTokenResponse, error)

	// Error can be either of the following types:
	//
	//   - ApprovalException
	//   - UserDoesntFullfillEndEntityProfile
	//   - AuthorizationDeniedException
	//   - EjbcaException
	//   - CesecoreException
	//   - CertificateExpiredException
	//   - WaitingForApprovalException
	//   - NotFoundException

	CvcRequest(request *CvcRequest) (*CvcRequestResponse, error)

	CvcRequestContext(ctx context.Context, request *CvcRequest) (*CvcRequestResponse, error)

	// Error can be either of the following types:
	//
	//   - EjbcaException

	IsAuthorized(request *IsAuthorized) (*IsAuthorizedResponse, error)

	IsAuthorizedContext(ctx context.Context, request *IsAuthorized) (*IsAuthorizedResponse, error)

	// Error can be either of the following types:
	//
	//   - AuthorizationDeniedException
	//   - EjbcaException
	//   - WaitingForApprovalException
	//   - NotFoundException
	//   - CADoesntExistsException

	KeyRecoverEnroll(request *KeyRecoverEnroll) (*KeyRecoverEnrollResponse, error)

	KeyRecoverEnrollContext(ctx context.Context, request *KeyRecoverEnroll) (*KeyRecoverEnrollResponse, error)

	// Error can be either of the following types:
	//
	//   - AuthorizationDeniedException
	//   - EjbcaException
	//   - CADoesntExistsException

	RepublishCertificate(request *RepublishCertificate) (*RepublishCertificateResponse, error)

	RepublishCertificateContext(ctx context.Context, request *RepublishCertificate) (*RepublishCertificateResponse, error)

	// Error can be either of the following types:
	//
	//   - ApprovalException
	//   - AuthorizationDeniedException
	//   - EjbcaException
	//   - CesecoreException
	//   - WaitingForApprovalException

	CaCertResponse(request *CaCertResponse) (*CaCertResponseResponse, error)

	CaCertResponseContext(ctx context.Context, request *CaCertResponse) (*CaCertResponseResponse, error)

	// Error can be either of the following types:
	//
	//   - ApprovalException
	//   - CryptoTokenOfflineException
	//   - EjbcaException
	//   - CAOfflineException
	//   - DeltaCrlException
	//   - CADoesntExistsException

	CreateCRL(request *CreateCRL) (*CreateCRLResponse, error)

	CreateCRLContext(ctx context.Context, request *CreateCRL) (*CreateCRLResponse, error)

	// Error can be either of the following types:
	//
	//   - AuthorizationDeniedException
	//   - EjbcaException

	GetAvailableCAsInProfile(request *GetAvailableCAsInProfile) (*GetAvailableCAsInProfileResponse, error)

	GetAvailableCAsInProfileContext(ctx context.Context, request *GetAvailableCAsInProfile) (*GetAvailableCAsInProfileResponse, error)

	// Error can be either of the following types:
	//
	//   - AuthorizationDeniedException
	//   - EjbcaException
	//   - NotFoundException
	//   - CADoesntExistsException

	Pkcs12Req(request *Pkcs12Req) (*Pkcs12ReqResponse, error)

	Pkcs12ReqContext(ctx context.Context, request *Pkcs12Req) (*Pkcs12ReqResponse, error)

	// Error can be either of the following types:
	//
	//   - ApprovalException
	//   - AuthorizationDeniedException
	//   - EjbcaException
	//   - CesecoreException
	//   - WaitingForApprovalException

	CaCertResponseForRollover(request *CaCertResponseForRollover) (*CaCertResponseForRolloverResponse, error)

	CaCertResponseForRolloverContext(ctx context.Context, request *CaCertResponseForRollover) (*CaCertResponseForRolloverResponse, error)

	// Error can be either of the following types:
	//
	//   - ApprovalException
	//   - AuthorizationDeniedException
	//   - EjbcaException
	//   - WaitingForApprovalException
	//   - NotFoundException
	//   - CADoesntExistsException

	KeyRecover(request *KeyRecover) (*KeyRecoverResponse, error)

	KeyRecoverContext(ctx context.Context, request *KeyRecover) (*KeyRecoverResponse, error)

	// Error can be either of the following types:
	//
	//   - ApprovalException
	//   - AuthorizationDeniedException
	//   - EjbcaException
	//   - WaitingForApprovalException
	//   - NotFoundException
	//   - AlreadyRevokedException
	//   - RevokeBackDateNotAllowedForProfileException
	//   - CertificateProfileDoesNotExistException
	//   - CADoesntExistsException

	RevokeCertWithMetadata(request *RevokeCertWithMetadata) (*RevokeCertWithMetadataResponse, error)

	RevokeCertWithMetadataContext(ctx context.Context, request *RevokeCertWithMetadata) (*RevokeCertWithMetadataResponse, error)

	// Error can be either of the following types:
	//
	//   - AuthorizationDeniedException
	//   - EjbcaException
	//   - CADoesntExistsException

	RolloverCACert(request *RolloverCACert) (*RolloverCACertResponse, error)

	RolloverCACertContext(ctx context.Context, request *RolloverCACert) (*RolloverCACertResponse, error)

	// Error can be either of the following types:
	//
	//   - AuthorizationDeniedException
	//   - EjbcaException
	//   - CADoesntExistsException

	CaRenewCertRequest(request *CaRenewCertRequest) (*CaRenewCertRequestResponse, error)

	CaRenewCertRequestContext(ctx context.Context, request *CaRenewCertRequest) (*CaRenewCertRequestResponse, error)

	// Error can be either of the following types:
	//
	//   - AuthorizationDeniedException
	//   - EjbcaException

	FetchUserData(request *FetchUserData) (*FetchUserDataResponse, error)

	FetchUserDataContext(ctx context.Context, request *FetchUserData) (*FetchUserDataResponse, error)

	// Error can be either of the following types:
	//
	//   - AuthorizationDeniedException
	//   - EjbcaException
	//   - CesecoreException
	//   - NotFoundException

	Pkcs10Request(request *Pkcs10Request) (*Pkcs10RequestResponse, error)

	Pkcs10RequestContext(ctx context.Context, request *Pkcs10Request) (*Pkcs10RequestResponse, error)

	// Error can be either of the following types:
	//
	//   - EjbcaException

	GetHardTokenDatas(request *GetHardTokenDatas) (*GetHardTokenDatasResponse, error)

	GetHardTokenDatasContext(ctx context.Context, request *GetHardTokenDatas) (*GetHardTokenDatasResponse, error)

	// Error can be either of the following types:
	//
	//   - ApprovalException
	//   - EjbcaException
	//   - NotFoundException
	//   - AlreadyRevokedException

	RevokeToken(request *RevokeToken) (*RevokeTokenResponse, error)

	RevokeTokenContext(ctx context.Context, request *RevokeToken) (*RevokeTokenResponse, error)

	// Error can be either of the following types:
	//
	//   - ApprovalException
	//   - AuthorizationDeniedException
	//   - UserDoesntFullfillEndEntityProfile
	//   - EjbcaException
	//   - NotFoundException
	//   - CADoesntExistsException

	SoftTokenRequest(request *SoftTokenRequest) (*SoftTokenRequestResponse, error)

	SoftTokenRequestContext(ctx context.Context, request *SoftTokenRequest) (*SoftTokenRequestResponse, error)

	// Error can be either of the following types:
	//
	//   - EjbcaException
	//   - CADoesntExistsException

	GetLatestCRL(request *GetLatestCRL) (*GetLatestCRLResponse, error)

	GetLatestCRLContext(ctx context.Context, request *GetLatestCRL) (*GetLatestCRLResponse, error)

	// Error can be either of the following types:
	//
	//   - AuthorizationDeniedException
	//   - EjbcaException
	//   - EndEntityProfileValidationException

	EnrollAndIssueSshCertificate(request *EnrollAndIssueSshCertificate) (*EnrollAndIssueSshCertificateResponse, error)

	EnrollAndIssueSshCertificateContext(ctx context.Context, request *EnrollAndIssueSshCertificate) (*EnrollAndIssueSshCertificateResponse, error)

	// Error can be either of the following types:
	//
	//   - AuthorizationDeniedException
	//   - EjbcaException

	ImportCaCert(request *ImportCaCert) (*ImportCaCertResponse, error)

	ImportCaCertContext(ctx context.Context, request *ImportCaCert) (*ImportCaCertResponse, error)

	// Error can be either of the following types:
	//
	//   - AuthorizationDeniedException
	//   - EjbcaException

	RemoveSubjectFromRole(request *RemoveSubjectFromRole) (*RemoveSubjectFromRoleResponse, error)

	RemoveSubjectFromRoleContext(ctx context.Context, request *RemoveSubjectFromRole) (*RemoveSubjectFromRoleResponse, error)

	// Error can be either of the following types:
	//
	//   - AuthorizationDeniedException
	//   - EjbcaException

	GetAvailableCAs(request *GetAvailableCAs) (*GetAvailableCAsResponse, error)

	GetAvailableCAsContext(ctx context.Context, request *GetAvailableCAs) (*GetAvailableCAsResponse, error)

	// Error can be either of the following types:
	//
	//   - EjbcaException

	GetCertificatesByExpirationTimeAndIssuer(request *GetCertificatesByExpirationTimeAndIssuer) (*GetCertificatesByExpirationTimeAndIssuerResponse, error)

	GetCertificatesByExpirationTimeAndIssuerContext(ctx context.Context, request *GetCertificatesByExpirationTimeAndIssuer) (*GetCertificatesByExpirationTimeAndIssuerResponse, error)

	// Error can be either of the following types:
	//
	//   - EjbcaException

	UpdateCaCert(request *UpdateCaCert) (*UpdateCaCertResponse, error)

	UpdateCaCertContext(ctx context.Context, request *UpdateCaCert) (*UpdateCaCertResponse, error)

	// Error can be either of the following types:
	//
	//   - AuthorizationDeniedException
	//   - EjbcaException

	GetLastCertChain(request *GetLastCertChain) (*GetLastCertChainResponse, error)

	GetLastCertChainContext(ctx context.Context, request *GetLastCertChain) (*GetLastCertChainResponse, error)

	// Error can be either of the following types:
	//
	//   - EjbcaException

	GetCertificatesByExpirationTime(request *GetCertificatesByExpirationTime) (*GetCertificatesByExpirationTimeResponse, error)

	GetCertificatesByExpirationTimeContext(ctx context.Context, request *GetCertificatesByExpirationTime) (*GetCertificatesByExpirationTimeResponse, error)

	// Error can be either of the following types:
	//
	//   - SshKeyException
	//   - CADoesntExistsException

	GetSshCaPublicKey(request *GetSshCaPublicKey) (*GetSshCaPublicKeyResponse, error)

	GetSshCaPublicKeyContext(ctx context.Context, request *GetSshCaPublicKey) (*GetSshCaPublicKeyResponse, error)

	// Error can be either of the following types:
	//
	//   - AuthorizationDeniedException
	//   - EjbcaException

	GetAvailableCertificateProfiles(request *GetAvailableCertificateProfiles) (*GetAvailableCertificateProfilesResponse, error)

	GetAvailableCertificateProfilesContext(ctx context.Context, request *GetAvailableCertificateProfiles) (*GetAvailableCertificateProfilesResponse, error)

	// Error can be either of the following types:
	//
	//   - AuthorizationDeniedException
	//   - EjbcaException

	CreateCA(request *CreateCA) (*CreateCAResponse, error)

	CreateCAContext(ctx context.Context, request *CreateCA) (*CreateCAResponse, error)

	// Error can be either of the following types:
	//
	//   - ApprovalException
	//   - EjbcaException
	//   - ApprovalRequestExpiredException

	IsApproved(request *IsApproved) (*IsApprovedResponse, error)

	IsApprovedContext(ctx context.Context, request *IsApproved) (*IsApprovedResponse, error)

	// Error can be either of the following types:
	//
	//   - EjbcaException

	CreateExternallySignedCa(request *CreateExternallySignedCa) (*CreateExternallySignedCaResponse, error)

	CreateExternallySignedCaContext(ctx context.Context, request *CreateExternallySignedCa) (*CreateExternallySignedCaResponse, error)

	// Error can be either of the following types:
	//
	//   - ApprovalException
	//   - AuthorizationDeniedException
	//   - EjbcaException
	//   - WaitingForApprovalException
	//   - NotFoundException
	//   - AlreadyRevokedException
	//   - CADoesntExistsException

	RevokeUser(request *RevokeUser) (*RevokeUserResponse, error)

	RevokeUserContext(ctx context.Context, request *RevokeUser) (*RevokeUserResponse, error)

	// Error can be either of the following types:
	//
	//   - ApprovalException
	//   - AuthorizationDeniedException
	//   - EjbcaException
	//   - WaitingForApprovalException
	//   - NotFoundException
	//   - AlreadyRevokedException
	//   - CADoesntExistsException

	RevokeCert(request *RevokeCert) (*RevokeCertResponse, error)

	RevokeCertContext(ctx context.Context, request *RevokeCert) (*RevokeCertResponse, error)

	// Error can be either of the following types:
	//
	//   - AuthorizationDeniedException
	//   - EjbcaException
	//   - CADoesntExistsException

	GetCertificate(request *GetCertificate) (*GetCertificateResponse, error)

	GetCertificateContext(ctx context.Context, request *GetCertificate) (*GetCertificateResponse, error)

	// Error can be either of the following types:
	//
	//   - EjbcaException

	GetPublisherQueueLength(request *GetPublisherQueueLength) (*GetPublisherQueueLengthResponse, error)

	GetPublisherQueueLengthContext(ctx context.Context, request *GetPublisherQueueLength) (*GetPublisherQueueLengthResponse, error)
}

type ejbcaWS struct {
	client *soap.Client
}

func NewEjbcaWS(client *soap.Client) EjbcaWS {
	return &ejbcaWS{
		client: client,
	}
}

func (service *ejbcaWS) GetHardTokenDataContext(ctx context.Context, request *GetHardTokenData) (*GetHardTokenDataResponse, error) {
	response := new(GetHardTokenDataResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/getHardTokenData", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) GetHardTokenData(request *GetHardTokenData) (*GetHardTokenDataResponse, error) {
	return service.GetHardTokenDataContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) GetProfileContext(ctx context.Context, request *GetProfile) (*GetProfileResponse, error) {
	response := new(GetProfileResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/getProfile", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) GetProfile(request *GetProfile) (*GetProfileResponse, error) {
	return service.GetProfileContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) CreateCryptoTokenContext(ctx context.Context, request *CreateCryptoToken) (*CreateCryptoTokenResponse, error) {
	response := new(CreateCryptoTokenResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/createCryptoToken", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) CreateCryptoToken(request *CreateCryptoToken) (*CreateCryptoTokenResponse, error) {
	return service.CreateCryptoTokenContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) CrmfRequestContext(ctx context.Context, request *CrmfRequest) (*CrmfRequestResponse, error) {
	response := new(CrmfRequestResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/crmfRequest", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) CrmfRequest(request *CrmfRequest) (*CrmfRequestResponse, error) {
	return service.CrmfRequestContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) FindUserContext(ctx context.Context, request *FindUser) (*FindUserResponse, error) {
	response := new(FindUserResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/findUser", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) FindUser(request *FindUser) (*FindUserResponse, error) {
	return service.FindUserContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) GetRemainingNumberOfApprovalsContext(ctx context.Context, request *GetRemainingNumberOfApprovals) (*GetRemainingNumberOfApprovalsResponse, error) {
	response := new(GetRemainingNumberOfApprovalsResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/getRemainingNumberOfApprovals", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) GetRemainingNumberOfApprovals(request *GetRemainingNumberOfApprovals) (*GetRemainingNumberOfApprovalsResponse, error) {
	return service.GetRemainingNumberOfApprovalsContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) GenTokenCertificatesContext(ctx context.Context, request *GenTokenCertificates) (*GenTokenCertificatesResponse, error) {
	response := new(GenTokenCertificatesResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/genTokenCertificates", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) GenTokenCertificates(request *GenTokenCertificates) (*GenTokenCertificatesResponse, error) {
	return service.GenTokenCertificatesContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) GetCertificatesByExpirationTimeAndTypeContext(ctx context.Context, request *GetCertificatesByExpirationTimeAndType) (*GetCertificatesByExpirationTimeAndTypeResponse, error) {
	response := new(GetCertificatesByExpirationTimeAndTypeResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/getCertificatesByExpirationTimeAndType", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) GetCertificatesByExpirationTimeAndType(request *GetCertificatesByExpirationTimeAndType) (*GetCertificatesByExpirationTimeAndTypeResponse, error) {
	return service.GetCertificatesByExpirationTimeAndTypeContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) RevokeCertBackdatedContext(ctx context.Context, request *RevokeCertBackdated) (*RevokeCertBackdatedResponse, error) {
	response := new(RevokeCertBackdatedResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/revokeCertBackdated", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) RevokeCertBackdated(request *RevokeCertBackdated) (*RevokeCertBackdatedResponse, error) {
	return service.RevokeCertBackdatedContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) CheckRevokationStatusContext(ctx context.Context, request *CheckRevokationStatus) (*CheckRevokationStatusResponse, error) {
	response := new(CheckRevokationStatusResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/checkRevokationStatus", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) CheckRevokationStatus(request *CheckRevokationStatus) (*CheckRevokationStatusResponse, error) {
	return service.CheckRevokationStatusContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) GenerateCryptoTokenKeysContext(ctx context.Context, request *GenerateCryptoTokenKeys) (*GenerateCryptoTokenKeysResponse, error) {
	response := new(GenerateCryptoTokenKeysResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/generateCryptoTokenKeys", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) GenerateCryptoTokenKeys(request *GenerateCryptoTokenKeys) (*GenerateCryptoTokenKeysResponse, error) {
	return service.GenerateCryptoTokenKeysContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) KeyRecoverNewestContext(ctx context.Context, request *KeyRecoverNewest) (*KeyRecoverNewestResponse, error) {
	response := new(KeyRecoverNewestResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/keyRecoverNewest", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) KeyRecoverNewest(request *KeyRecoverNewest) (*KeyRecoverNewestResponse, error) {
	return service.KeyRecoverNewestContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) EditUserContext(ctx context.Context, request *EditUser) (*EditUserResponse, error) {
	response := new(EditUserResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/editUser", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) EditUser(request *EditUser) (*EditUserResponse, error) {
	return service.EditUserContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) SpkacRequestContext(ctx context.Context, request *SpkacRequest) (*SpkacRequestResponse, error) {
	response := new(SpkacRequestResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/spkacRequest", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) SpkacRequest(request *SpkacRequest) (*SpkacRequestResponse, error) {
	return service.SpkacRequestContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) GetLatestCRLPartitionContext(ctx context.Context, request *GetLatestCRLPartition) (*GetLatestCRLPartitionResponse, error) {
	response := new(GetLatestCRLPartitionResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/getLatestCRLPartition", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) GetLatestCRLPartition(request *GetLatestCRLPartition) (*GetLatestCRLPartitionResponse, error) {
	return service.GetLatestCRLPartitionContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) GetLastCAChainContext(ctx context.Context, request *GetLastCAChain) (*GetLastCAChainResponse, error) {
	response := new(GetLastCAChainResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/getLastCAChain", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) GetLastCAChain(request *GetLastCAChain) (*GetLastCAChainResponse, error) {
	return service.GetLastCAChainContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) AddSubjectToRoleContext(ctx context.Context, request *AddSubjectToRole) (*AddSubjectToRoleResponse, error) {
	response := new(AddSubjectToRoleResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/addSubjectToRole", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) AddSubjectToRole(request *AddSubjectToRole) (*AddSubjectToRoleResponse, error) {
	return service.AddSubjectToRoleContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) FindCertsContext(ctx context.Context, request *FindCerts) (*FindCertsResponse, error) {
	response := new(FindCertsResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/findCerts", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) FindCerts(request *FindCerts) (*FindCertsResponse, error) {
	return service.FindCertsContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) DeleteUserDataFromSourceContext(ctx context.Context, request *DeleteUserDataFromSource) (*DeleteUserDataFromSourceResponse, error) {
	response := new(DeleteUserDataFromSourceResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/deleteUserDataFromSource", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) DeleteUserDataFromSource(request *DeleteUserDataFromSource) (*DeleteUserDataFromSourceResponse, error) {
	return service.DeleteUserDataFromSourceContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) CertificateRequestContext(ctx context.Context, request *CertificateRequest) (*CertificateRequestResponse, error) {
	response := new(CertificateRequestResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/certificateRequest", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) CertificateRequest(request *CertificateRequest) (*CertificateRequestResponse, error) {
	return service.CertificateRequestContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) CustomLogContext(ctx context.Context, request *CustomLog) (*CustomLogResponse, error) {
	response := new(CustomLogResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/customLog", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) CustomLog(request *CustomLog) (*CustomLogResponse, error) {
	return service.CustomLogContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) GetEjbcaVersionContext(ctx context.Context, request *GetEjbcaVersion) (*GetEjbcaVersionResponse, error) {
	response := new(GetEjbcaVersionResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/getEjbcaVersion", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) GetEjbcaVersion(request *GetEjbcaVersion) (*GetEjbcaVersionResponse, error) {
	return service.GetEjbcaVersionContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) GetAuthorizedEndEntityProfilesContext(ctx context.Context, request *GetAuthorizedEndEntityProfiles) (*GetAuthorizedEndEntityProfilesResponse, error) {
	response := new(GetAuthorizedEndEntityProfilesResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/getAuthorizedEndEntityProfiles", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) GetAuthorizedEndEntityProfiles(request *GetAuthorizedEndEntityProfiles) (*GetAuthorizedEndEntityProfilesResponse, error) {
	return service.GetAuthorizedEndEntityProfilesContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) ExistsHardTokenContext(ctx context.Context, request *ExistsHardToken) (*ExistsHardTokenResponse, error) {
	response := new(ExistsHardTokenResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/existsHardToken", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) ExistsHardToken(request *ExistsHardToken) (*ExistsHardTokenResponse, error) {
	return service.ExistsHardTokenContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) CvcRequestContext(ctx context.Context, request *CvcRequest) (*CvcRequestResponse, error) {
	response := new(CvcRequestResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/cvcRequest", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) CvcRequest(request *CvcRequest) (*CvcRequestResponse, error) {
	return service.CvcRequestContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) IsAuthorizedContext(ctx context.Context, request *IsAuthorized) (*IsAuthorizedResponse, error) {
	response := new(IsAuthorizedResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/isAuthorized", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) IsAuthorized(request *IsAuthorized) (*IsAuthorizedResponse, error) {
	return service.IsAuthorizedContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) KeyRecoverEnrollContext(ctx context.Context, request *KeyRecoverEnroll) (*KeyRecoverEnrollResponse, error) {
	response := new(KeyRecoverEnrollResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/keyRecoverEnroll", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) KeyRecoverEnroll(request *KeyRecoverEnroll) (*KeyRecoverEnrollResponse, error) {
	return service.KeyRecoverEnrollContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) RepublishCertificateContext(ctx context.Context, request *RepublishCertificate) (*RepublishCertificateResponse, error) {
	response := new(RepublishCertificateResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/republishCertificate", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) RepublishCertificate(request *RepublishCertificate) (*RepublishCertificateResponse, error) {
	return service.RepublishCertificateContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) CaCertResponseContext(ctx context.Context, request *CaCertResponse) (*CaCertResponseResponse, error) {
	response := new(CaCertResponseResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/caCertResponse", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) CaCertResponse(request *CaCertResponse) (*CaCertResponseResponse, error) {
	return service.CaCertResponseContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) CreateCRLContext(ctx context.Context, request *CreateCRL) (*CreateCRLResponse, error) {
	response := new(CreateCRLResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/createCRL", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) CreateCRL(request *CreateCRL) (*CreateCRLResponse, error) {
	return service.CreateCRLContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) GetAvailableCAsInProfileContext(ctx context.Context, request *GetAvailableCAsInProfile) (*GetAvailableCAsInProfileResponse, error) {
	response := new(GetAvailableCAsInProfileResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/getAvailableCAsInProfile", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) GetAvailableCAsInProfile(request *GetAvailableCAsInProfile) (*GetAvailableCAsInProfileResponse, error) {
	return service.GetAvailableCAsInProfileContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) Pkcs12ReqContext(ctx context.Context, request *Pkcs12Req) (*Pkcs12ReqResponse, error) {
	response := new(Pkcs12ReqResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/pkcs12Req", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) Pkcs12Req(request *Pkcs12Req) (*Pkcs12ReqResponse, error) {
	return service.Pkcs12ReqContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) CaCertResponseForRolloverContext(ctx context.Context, request *CaCertResponseForRollover) (*CaCertResponseForRolloverResponse, error) {
	response := new(CaCertResponseForRolloverResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/caCertResponseForRollover", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) CaCertResponseForRollover(request *CaCertResponseForRollover) (*CaCertResponseForRolloverResponse, error) {
	return service.CaCertResponseForRolloverContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) KeyRecoverContext(ctx context.Context, request *KeyRecover) (*KeyRecoverResponse, error) {
	response := new(KeyRecoverResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/keyRecover", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) KeyRecover(request *KeyRecover) (*KeyRecoverResponse, error) {
	return service.KeyRecoverContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) RevokeCertWithMetadataContext(ctx context.Context, request *RevokeCertWithMetadata) (*RevokeCertWithMetadataResponse, error) {
	response := new(RevokeCertWithMetadataResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/revokeCertWithMetadata", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) RevokeCertWithMetadata(request *RevokeCertWithMetadata) (*RevokeCertWithMetadataResponse, error) {
	return service.RevokeCertWithMetadataContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) RolloverCACertContext(ctx context.Context, request *RolloverCACert) (*RolloverCACertResponse, error) {
	response := new(RolloverCACertResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/rolloverCACert", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) RolloverCACert(request *RolloverCACert) (*RolloverCACertResponse, error) {
	return service.RolloverCACertContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) CaRenewCertRequestContext(ctx context.Context, request *CaRenewCertRequest) (*CaRenewCertRequestResponse, error) {
	response := new(CaRenewCertRequestResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/caRenewCertRequest", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) CaRenewCertRequest(request *CaRenewCertRequest) (*CaRenewCertRequestResponse, error) {
	return service.CaRenewCertRequestContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) FetchUserDataContext(ctx context.Context, request *FetchUserData) (*FetchUserDataResponse, error) {
	response := new(FetchUserDataResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/fetchUserData", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) FetchUserData(request *FetchUserData) (*FetchUserDataResponse, error) {
	return service.FetchUserDataContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) Pkcs10RequestContext(ctx context.Context, request *Pkcs10Request) (*Pkcs10RequestResponse, error) {
	response := new(Pkcs10RequestResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/pkcs10Request", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) Pkcs10Request(request *Pkcs10Request) (*Pkcs10RequestResponse, error) {
	return service.Pkcs10RequestContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) GetHardTokenDatasContext(ctx context.Context, request *GetHardTokenDatas) (*GetHardTokenDatasResponse, error) {
	response := new(GetHardTokenDatasResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/getHardTokenDatas", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) GetHardTokenDatas(request *GetHardTokenDatas) (*GetHardTokenDatasResponse, error) {
	return service.GetHardTokenDatasContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) RevokeTokenContext(ctx context.Context, request *RevokeToken) (*RevokeTokenResponse, error) {
	response := new(RevokeTokenResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/revokeToken", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) RevokeToken(request *RevokeToken) (*RevokeTokenResponse, error) {
	return service.RevokeTokenContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) SoftTokenRequestContext(ctx context.Context, request *SoftTokenRequest) (*SoftTokenRequestResponse, error) {
	response := new(SoftTokenRequestResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/softTokenRequest", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) SoftTokenRequest(request *SoftTokenRequest) (*SoftTokenRequestResponse, error) {
	return service.SoftTokenRequestContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) GetLatestCRLContext(ctx context.Context, request *GetLatestCRL) (*GetLatestCRLResponse, error) {
	response := new(GetLatestCRLResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/getLatestCRL", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) GetLatestCRL(request *GetLatestCRL) (*GetLatestCRLResponse, error) {
	return service.GetLatestCRLContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) EnrollAndIssueSshCertificateContext(ctx context.Context, request *EnrollAndIssueSshCertificate) (*EnrollAndIssueSshCertificateResponse, error) {
	response := new(EnrollAndIssueSshCertificateResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/enrollAndIssueSshCertificate", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) EnrollAndIssueSshCertificate(request *EnrollAndIssueSshCertificate) (*EnrollAndIssueSshCertificateResponse, error) {
	return service.EnrollAndIssueSshCertificateContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) ImportCaCertContext(ctx context.Context, request *ImportCaCert) (*ImportCaCertResponse, error) {
	response := new(ImportCaCertResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/importCaCert", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) ImportCaCert(request *ImportCaCert) (*ImportCaCertResponse, error) {
	return service.ImportCaCertContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) RemoveSubjectFromRoleContext(ctx context.Context, request *RemoveSubjectFromRole) (*RemoveSubjectFromRoleResponse, error) {
	response := new(RemoveSubjectFromRoleResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/removeSubjectFromRole", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) RemoveSubjectFromRole(request *RemoveSubjectFromRole) (*RemoveSubjectFromRoleResponse, error) {
	return service.RemoveSubjectFromRoleContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) GetAvailableCAsContext(ctx context.Context, request *GetAvailableCAs) (*GetAvailableCAsResponse, error) {
	response := new(GetAvailableCAsResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/getAvailableCAs", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) GetAvailableCAs(request *GetAvailableCAs) (*GetAvailableCAsResponse, error) {
	return service.GetAvailableCAsContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) GetCertificatesByExpirationTimeAndIssuerContext(ctx context.Context, request *GetCertificatesByExpirationTimeAndIssuer) (*GetCertificatesByExpirationTimeAndIssuerResponse, error) {
	response := new(GetCertificatesByExpirationTimeAndIssuerResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/getCertificatesByExpirationTimeAndIssuer", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) GetCertificatesByExpirationTimeAndIssuer(request *GetCertificatesByExpirationTimeAndIssuer) (*GetCertificatesByExpirationTimeAndIssuerResponse, error) {
	return service.GetCertificatesByExpirationTimeAndIssuerContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) UpdateCaCertContext(ctx context.Context, request *UpdateCaCert) (*UpdateCaCertResponse, error) {
	response := new(UpdateCaCertResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/updateCaCert", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) UpdateCaCert(request *UpdateCaCert) (*UpdateCaCertResponse, error) {
	return service.UpdateCaCertContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) GetLastCertChainContext(ctx context.Context, request *GetLastCertChain) (*GetLastCertChainResponse, error) {
	response := new(GetLastCertChainResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/getLastCertChain", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) GetLastCertChain(request *GetLastCertChain) (*GetLastCertChainResponse, error) {
	return service.GetLastCertChainContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) GetCertificatesByExpirationTimeContext(ctx context.Context, request *GetCertificatesByExpirationTime) (*GetCertificatesByExpirationTimeResponse, error) {
	response := new(GetCertificatesByExpirationTimeResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/getCertificatesByExpirationTime", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) GetCertificatesByExpirationTime(request *GetCertificatesByExpirationTime) (*GetCertificatesByExpirationTimeResponse, error) {
	return service.GetCertificatesByExpirationTimeContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) GetSshCaPublicKeyContext(ctx context.Context, request *GetSshCaPublicKey) (*GetSshCaPublicKeyResponse, error) {
	response := new(GetSshCaPublicKeyResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/getSshCaPublicKey", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) GetSshCaPublicKey(request *GetSshCaPublicKey) (*GetSshCaPublicKeyResponse, error) {
	return service.GetSshCaPublicKeyContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) GetAvailableCertificateProfilesContext(ctx context.Context, request *GetAvailableCertificateProfiles) (*GetAvailableCertificateProfilesResponse, error) {
	response := new(GetAvailableCertificateProfilesResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/getAvailableCertificateProfiles", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) GetAvailableCertificateProfiles(request *GetAvailableCertificateProfiles) (*GetAvailableCertificateProfilesResponse, error) {
	return service.GetAvailableCertificateProfilesContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) CreateCAContext(ctx context.Context, request *CreateCA) (*CreateCAResponse, error) {
	response := new(CreateCAResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/createCA", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) CreateCA(request *CreateCA) (*CreateCAResponse, error) {
	return service.CreateCAContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) IsApprovedContext(ctx context.Context, request *IsApproved) (*IsApprovedResponse, error) {
	response := new(IsApprovedResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/isApproved", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) IsApproved(request *IsApproved) (*IsApprovedResponse, error) {
	return service.IsApprovedContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) CreateExternallySignedCaContext(ctx context.Context, request *CreateExternallySignedCa) (*CreateExternallySignedCaResponse, error) {
	response := new(CreateExternallySignedCaResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/createExternallySignedCa", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) CreateExternallySignedCa(request *CreateExternallySignedCa) (*CreateExternallySignedCaResponse, error) {
	return service.CreateExternallySignedCaContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) RevokeUserContext(ctx context.Context, request *RevokeUser) (*RevokeUserResponse, error) {
	response := new(RevokeUserResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/revokeUser", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) RevokeUser(request *RevokeUser) (*RevokeUserResponse, error) {
	return service.RevokeUserContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) RevokeCertContext(ctx context.Context, request *RevokeCert) (*RevokeCertResponse, error) {
	response := new(RevokeCertResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/revokeCert", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) RevokeCert(request *RevokeCert) (*RevokeCertResponse, error) {
	return service.RevokeCertContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) GetCertificateContext(ctx context.Context, request *GetCertificate) (*GetCertificateResponse, error) {
	response := new(GetCertificateResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/getCertificate", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) GetCertificate(request *GetCertificate) (*GetCertificateResponse, error) {
	return service.GetCertificateContext(
		context.Background(),
		request,
	)
}

func (service *ejbcaWS) GetPublisherQueueLengthContext(ctx context.Context, request *GetPublisherQueueLength) (*GetPublisherQueueLengthResponse, error) {
	response := new(GetPublisherQueueLengthResponse)
	err := service.client.CallContext(ctx, "http://ws.protocol.core.ejbca.org/getPublisherQueueLength", request, response)
	if err != nil {
		return nil, err
	}

	return response, nil
}

func (service *ejbcaWS) GetPublisherQueueLength(request *GetPublisherQueueLength) (*GetPublisherQueueLengthResponse, error) {
	return service.GetPublisherQueueLengthContext(
		context.Background(),
		request,
	)
}
